### ISSUE TITLE
missing dependency...

### ISSUE THREAD

**Issue by buedi** [jpro-one/HelloJPro#1]
The dependency to the import of JProApplication is missing.

Best regards 
Daniel

C:\Users\user\Downloads\HelloJPro-master>gradle jproRun
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_6x9wpnwgqmvlmplwbkm8ng1f8.run(C:\Users\buedenbenderd\Downloads\HelloJPro-master\build.gradle:42)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

> Task :compileJava FAILED
C:\Users\user\Downloads\HelloJPro-master\src\main\java\com\jpro\hellojpro\HelloJProController.java:3: error: cannot find symbol
import com.jpro.webapi.JProApplication;
                      ^
  symbol:   class JProApplication
  location: package com.jpro.webapi
C:\Users\user\Downloads\HelloJPro-master\src\main\java\com\jpro\hellojpro\HelloJProController.java:31: error: cannot find symbol
    protected JProApplication jProApplication;
              ^
  symbol:   class JProApplication
  location: class HelloJProController
C:\Users\user\Downloads\HelloJPro-master\src\main\java\com\jpro\hellojpro\HelloJProController.java:61: error: cannot find symbol
    public void init(JProApplication jProApplication)

**Comment by FlorianKirmaier** [comment]
Hi Daniel,

Thank You for your feedback.
I updated the project to the latest version.
It should work now.

Greetings Florian Kirmaier
