### ISSUE TITLE
Can I change or remove the loading view?

### ISSUE THREAD

**Issue by ashokkumarvel** [JPro-one/HelloJPro#12]
When I run JPro in browser it first loading like this

![jpro](https://user-images.githubusercontent.com/65845270/84591637-b203b380-ae5d-11ea-9e71-e33261c18fd5.PNG)

Can I change the loading image ?

(or)

Can I remove it ?

**Comment by ashokkumarvel** [comment]
Is it possible?

**Comment by FlorianKirmaier** [comment]
Please ask questions which are not about the Sample in [JPro-Tickets](https://github.com/JPro-one/JPro-tickets)
In the JProTag, you can set `loader="none"` to disable the loader.
There is a ticket about changing the loader: https://github.com/JPro-one/JPro-tickets/issues/15
We will add it to our next minor update.
