### ISSUE TITLE
Could not resolve com.sandec.jpro:jpro-plugin-gradle:2020.1.4

### ISSUE THREAD

**Issue by mipastgt** [JPro-one/HelloJPro#14]
I just cloned this repo and tried to run `./gradlew jproRun` but all I got was this:

(Same for the Maven variant)

```
* What went wrong:
A problem occurred configuring root project 'HelloJPro'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.sandec.jpro:jpro-plugin-gradle:2020.1.4.
     Required by:
         project :
      > Could not resolve com.sandec.jpro:jpro-plugin-gradle:2020.1.4.
         > Could not get resource 'https://sandec.bintray.com/repo/com/sandec/jpro/jpro-plugin-gradle/2020.1.4/jpro-plugin-gradle-2020.1.4.pom'.
            > Could not GET 'https://sandec.bintray.com/repo/com/sandec/jpro/jpro-plugin-gradle/2020.1.4/jpro-plugin-gradle-2020.1.4.pom'. Received status code 403 from server: Forbidden
```

**Comment by FlorianKirmaier** [comment]
Sorry, we are a bit late with moving away from Bintray. It should soon work again.

**Comment by mipastgt** [comment]
Do you already have a rough schedule for that? (Just for my internal planning.)

**Comment by FlorianKirmaier** [comment]
Forgot to mention, it's working since yesterday evening again. It was only down for some hours. It was a simulated downtime, so people move away from Bintray before they shut it down, at the end of the month.
We plan to provide an alternative repository later this week.

**Comment by mipastgt** [comment]
Thanks
