### ISSUE TITLE
InaccessibleObjectException when running code

### ISSUE THREAD

**Issue by aviperl** [JPro-one/HelloJPro#15]
When I execute `gradlew jproRun`, I get the following error message:

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.
ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @746c5eee
```

There appears to be some sort of issue with the module system.

**Comment by FlorianKirmaier** [comment]
Which Java version are you using? 
We currently only support up to Java15.

**Comment by aviperl** [comment]
I'm using Java 16. I guess that explains it. When do you believe Java 16 support will be added?

**Comment by FlorianKirmaier** [comment]
In the next major release, which will be out in few weeks.
I've looked into it and updated the Gradle version of the HelloWorld to be compatible with Java16.
To use Java16, you also have to add the following to the build.gradle `JVMArgs << "--illegal-access=permit"`(or something similar for maven)

**Comment by aviperl** [comment]
That worked. Thanks for all your help.

**Comment by FlorianKirmaier** [comment]
I've reopened the ticket because it's not fixed yet. 
There is only a workaround available.

**Comment by Kjothimani** [comment]
it is not working for maven aswell

**Comment by FlorianKirmaier** [comment]
@Kjothimani 
It should be working with the latest version (2021.1.1).
If the issue persists with this version, please reopen the ticket.

**Comment by shivaniy24** [comment]
Hi All

Recently we have migrated our code to java17, and while running tests we are getting below error : "Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang". Can you guys suggest what can be done here to fix this issue ?
Spring version : 5.3.26
java : zulu17

**Comment by FlorianKirmaier** [comment]
@shivaniy24 
Yes, but we need to know how to reproduce it.
Which zulu17 do you use? The one with or without JavaFX? You have to use the version without JavaFX.
If we can reproduce it - we can probably fix it. The easiest way would be to have a forked version of the HelloWorld, which reproduces the problem. Or instructions on how to reproduce it on the HelloJPro project.

**Comment by lucho2819** [comment]
Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4cdbe50f

**Comment by FlorianKirmaier** [comment]
@lucho2819 
If you want help, you must write more, especially JVM, OS, JProVersion, ideally in a new ticket.

**Comment by chudnikau** [comment]
Hello, it can be reproduced by adding mock(HandlerMethod.class) in test
