### ISSUE TITLE
native codes

### ISSUE THREAD

**Issue by johnpawl** [JPro-one/HelloJPro#16]
I want to make a javafx app wirth cmake .

I want to add c++ codes with javafx using cmake.

is it possible to run native code with jpro ?

**Comment by FlorianKirmaier** [comment]
Because JPro just runs on the JVM, it is possible add native code.
Combining JavaFX with cmake seems very unusual.
Using native code in JavaProjects isn't so uncommon, JavaFX for example.
JPro currently has a gradle and maven plugin, so I would recommend using these plugins to start the JProServer.

**Comment by johnpawl** [comment]
> Because JPro just runs on the JVM, it is possible add native code.
> Combining JavaFX with cmake seems very unusual.
> Using native code in JavaProjects isn't so uncommon, JavaFX for example.
> JPro currently has a gradle and maven plugin, so I would recommend using these plugins to start the JProServer.

**Thanks for your reply**
