### ISSUE TITLE
jpro failing to start

### ISSUE THREAD

**Issue by Lukvang** [jpro-one/HelloJPro#2]
Downloaded the master followed instructions to run but received the following:

`./gradlew jproRestart`

Received the following from terminal:

<img width="278" alt="screenshot 2018-04-11 10 49 17" src="https://user-images.githubusercontent.com/5392659/38628056-127d1202-3d76-11e8-8dc3-3522ec9f0070.png">

`./gradlew jproRun`

Received  the following from terminal: 
<img width="360" alt="screenshot 2018-04-11 10 51 24" src="https://user-images.githubusercontent.com/5392659/38628139-4c4eac98-3d76-11e8-984f-92146f49cde9.png">

**Comment by FlorianKirmaier** [comment]
On which Operating System did you try to run the HelloWorld?

In a headless server, some packages have to be installed, like gtk and x11.

I will updated the documentation about the requirements soon.

**Comment by Lukvang** [comment]
I'm using mac os high sierra v 10.13.3

**Comment by FlorianKirmaier** [comment]
It should work without any problems or preperation on mac, except installing java.
Whats the output of `./gradlew :jproRun` ? (From the top, to the first `Error-Code: 2`)

**Comment by FlorianKirmaier** [comment]
@Lukvang
I made a small change to the project, the debugging-options are now deactivated by default, which was the original intention.

Can you try it again with the newest version?

**Comment by Lukvang** [comment]
@FlorianKirmaier it's working now, i'm seeing the Hello World app run locally. Thanks!
