### ISSUE TITLE
How to set systemProperty ?

### ISSUE THREAD

**Issue by harideva16** [JPro-one/HelloJPro#21]
How can I set systemProperty `java.library.path` ?

I followed this https://stackoverflow.com/questions/23367507/how-to-pass-system-property-to-gradle-task

I added the following code in gradle.build file to set  systemProperty.

    task local {
        run {  systemProperty "java.library.path", file("${project(":hello").buildDir}/lib/main/debug").absolutePath }
    }

    bootRun.mustRunAfter local

But , it not worked.

How can I set systemProperty `java.library.path`  in gradle.build file ?

**Comment by harideva16** [comment]
I want to build JPRO on github actions.

so , I need to add systemProperty in gradle.build file.

Help me !!!

**Comment by harideva16** [comment]
usually I set jni library path like [this][1].

But, I didn't know about how to set system Property in gradle for all the three following os?

- Windows
- Linux
- Mac


How can I set systemProperty `java.library.path` ?

I followed this [answer][3]

I added the following code in gradle.build file to set  systemProperty.

    task local {
        run {  systemProperty "java.library.path", file("${project(":hello").buildDir}/lib/main/debug").absolutePath }
    }

    bootRun.mustRunAfter local

But , it not worked.

I followed this [project][2] to implement JNI . I searched in internet about how to set system properties for `java.library.path` in gradle . But , no answer found.

I  also asked a [question][4] in stackoverflow But , no response.

so, please help me !!!

If I run it comes an error like this `java.lang.UnsatisfiedLinkError: no hello in java.library.path`.

Can you give any documents or reference about it ?

How can I set systemProperty `java.library.path`  in gradle.build file ?

Give a answer!!!!

  [1]: https://stackoverflow.com/a/19311972/16522525
  [2]: https://github.com/vladsoroka/GradleJniSample/blob/master/build.gradle
  [3]: https://stackoverflow.com/a/23389443/16522525
  [4]: https://stackoverflow.com/questions/68757280/how-to-set-native-library-location-in-gradle

**Comment by harideva16** [comment]
[my path][1]

Can I set path like this ? is it right ?

    
![path](https://user-images.githubusercontent.com/88296348/129689956-b194d28f-b537-43c2-ac86-f7d76f8d4130.PNG)

I followed this [project][2] to implement JNI . Now , I confused about how to set this path `file("${project(":hello").buildDir}/lib/main/debug").absolutePath` in here `jpro.JVMArgs << '-Djava.library.path=something'`.

    jpro.JVMArgs << '-Djava.library.path=file("${project(":hello").buildDir}/lib/main/debug").absolutePath


  [1]: https://github.com/vladsoroka/GradleJniSample/blob/master/build.gradle#L20
  [2]: https://github.com/vladsoroka/GradleJniSample

**Comment by harideva16** [comment]
**I set the path successfully.**

    jpro.JVMArgs <<  '-Djava.library.path='+file("${project(":hello").buildDir}/lib/main/debug").absolutePath


**HelloJProFXML.java**

    public class HelloJProFXML extends JProApplication
    {


        public native void print();

        static {
        System.loadLibrary("hello");
        }

        public static void main(String[] args)
        {
        launch(args);
       }

       @Override
        public void start(Stage stage)
        {

        new HelloJProFXML().print();
        //load user interface as FXML file
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/com/jpro/hellojpro/fxml/HelloJPro.fxml"));
        Scene scene = null;
        try
        {
            Parent root = loader.load();
            HelloJProFXMLController controller = loader.getController();
            controller.init(this);

            //create JavaFX scene
            scene = new Scene(root);
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        stage.setTitle("Hello jpro!");
        stage.setScene(scene);

        //open JavaFX window
        stage.show();
    }
    }



But , error occured

        java.lang.UnsatisfiedLinkError: no hello in java.library.path
         	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        	at java.lang.System.loadLibrary(System.java:1124)
        	at HelloWorld.<clinit>(HelloJProFXML.java :18)

**Comment by poorvajappja** [comment]
@FlorianKirmaier I think it's not a right answer. 

Please check this : https://stackoverflow.com/a/59495773/10870644

**Comment by FlorianKirmaier** [comment]
I've only answered on how to add System properties. I didn't answer anything c++/"native compilation" related - which I don't know anything about. This is also not the right place to question anything related to gradle/c++ interactions.
