### ISSUE TITLE
How to set system Property java.library.path ?

### ISSUE THREAD

**Issue by harideva16** [JPro-one/HelloJPro#22]
I followed this project to generate JNI : https://github.com/vladsoroka/GradleJniSample/blob/master/hello/build.gradle#L14

But , It didn't generate native libs.

![files](https://user-images.githubusercontent.com/88296348/129856324-eaf7f51a-c4b4-4c62-8c74-fa0b9380ee2c.PNG)

**I set the path successfully.**

    jpro.JVMArgs <<  '-Djava.library.path='+file("${project(":hello").buildDir}/lib/main/debug").absolutePath

**HelloJProFXML.java**

    public class HelloJProFXML extends JProApplication
    {

        public native void print();

        static {
        System.loadLibrary("hello");
        }

        public static void main(String[] args)
        {
        launch(args);
       }

       @Override
        public void start(Stage stage)
        {

        new HelloJProFXML().print();
        //load user interface as FXML file
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/com/jpro/hellojpro/fxml/HelloJPro.fxml"));
        Scene scene = null;
        try
        {
            Parent root = loader.load();
            HelloJProFXMLController controller = loader.getController();
            controller.init(this);

            //create JavaFX scene
            scene = new Scene(root);
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }

        stage.setTitle("Hello jpro!");
        stage.setScene(scene);

        //open JavaFX window
        stage.show();
    }
    }

But , error occured

        java.lang.UnsatisfiedLinkError: no hello in java.library.path
         	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
        	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        	at java.lang.System.loadLibrary(System.java:1124)
        	at HelloWorld.<clinit>(HelloJProFXML.java :18)

This error was occured . because , this `file("${project(":hello").buildDir}/lib/main/debug").absolutePath` path does not contains `.dylib`

How can I generate `.dylib` ?

https://github.com/vladsoroka/GradleJniSample/blob/master/hello/build.gradle#L14

**Comment by poorvajappja** [comment]
@harideva16 all are correct. Problem in setting systemProperty `java.library.path`.

**Comment by parasuraam** [comment]
> @harideva16 all are correct. Problem in setting systemProperty `java.library.path`.

@poorvajappja yes, correct.

**Comment by poorvajappja** [comment]
Java native interface (jni) allows calling native libraries 

Windows  --> .dll
Linux         --> .so
Mac           -->.dylib


Issue  : https://github.com/JPro-one/HelloJPro/issues/22


So, @harideva16  using Windows. hello.dll file present in that screen shot. 

The problem in setting systemProperty path `java.library.path`.    

This answer is wrong   https://github.com/JPro-one/HelloJPro/issues/21#issuecomment-899541774 .

**Comment by harideva16** [comment]
@FlorianKirmaier How to set system Property `java.library.path` ?

this code not worked 
`jpro.JVMArgs <<  '-Djava.library.path='+file("${project(":hello").buildDir}/lib/main/debug").absolutePath
`

**Comment by harideva16** [comment]
@FlorianKirmaier How to set system Property `java.library.path` ?

this code not worked 
`jpro.JVMArgs <<  '-Djava.library.path='+file("${project(":hello").buildDir}/lib/main/debug").absolutePath`

**Comment by FlorianKirmaier** [comment]
The answer is only correct if you start it with ./gradlew jproRun. This will just add it to the commandline. You can check it with `ps aux | grep java` on unix or something similar on windows. The question is, how to do you start your application?

**Comment by harideva16** [comment]
> The answer is only correct if you start it with ./gradlew jproRun. This will just add it to the commandline. You can check it with `ps aux | grep java` on unix or something similar on windows. The question is, how to do you start your application?

sorry , It worked.
