### ISSUE TITLE
native library didn't work after releasing JPRO .

### ISSUE THREAD

**Issue by harideva16** [JPro-one/HelloJPro#25]
I created  a JPRO project with jni. it works soothly.

But , native library didn't work after releasing JPRO .

**Comment by FlorianKirmaier** [comment]
You might have to add the native library to the release, like the following:
`jproReleaseFiles << JProReleaseFile(new File("target/yourfile"), "/data/yourfile")`

You might also add different JVM arguments, dependent on whether you are using release, or you are running it with jproRun:
```
JVMArgs << '-Djvmargument'
localJVMArgs << '-Djvmargument'
releaseJVMArgs << '-Djvmargument'
```

**Comment by poorvajappja** [comment]
@FlorianKirmaier this ans is for jpro.
What can I do for normal javafx applications ?

**Comment by FlorianKirmaier** [comment]
The following works for `./gradlew run`:
```
application {
    applicationDefaultJvmArgs = ['-Dgreeting.language=en']
}
```

**Comment by poorvajappja** [comment]
@FlorianKirmaier I tried this code . But , after creating JPACKAGE native code not worked.

**Comment by FlorianKirmaier** [comment]
If you use jpackage directly, or you use it with some tool, you have to look into it's documentation. Probably quite simple.

**Comment by poorvajappja** [comment]
https://github.com/JPro-one/JPro-from-Jars/issues/14#issuecomment-656154493

I am using this plugin to create jpackage 
https://github.com/beryx-gist/badass-runtime-example-javafx
once upon a time you introduced this plugin .

**Comment by FlorianKirmaier** [comment]
Makes sense.
Check it's documentation and search for "JVMArg": https://badass-runtime-plugin.beryx.org/releases/latest/
You will probably find other useful details too.

**Comment by poorvajappja** [comment]
But , there is no information about jni and system property.

**Comment by FlorianKirmaier** [comment]
But you can set the JVMArgs, which can be used to set the System property.
Regarding packing native libraries, I don't know how to do it with the badass plugin. There are various options in the documentation you can try out. I'm sure there's a solution for it.

**Comment by harideva16** [comment]
launcher {
        noConsole = true
        jvmArgs = ['-Djava.library.path='+file("${project(":hello").buildDir}/lib/main/debug").absolutePath]
        unixScriptTemplate = file('unixStartScript.txt')
        windowsScriptTemplate = file('windowsStartScript.txt')
    }


[My project][1]

![jhgpath hhhjh](https://user-images.githubusercontent.com/88296348/131617856-7575cc36-c9f7-48a8-92d6-98442b840e14.PNG)

[build.gradle][2]

What I did wrong in this ?

why this error comes ?


  [1]: https://github.com/harideva16/pl
  [2]: https://github.com/harideva16/pl/blob/main/build.gradle#L56#L57

**Comment by harideva16** [comment]
> You might have to add the native library to the release, like the following:
> `jproReleaseFiles << JProReleaseFile(new File("target/yourfile"), "/data/yourfile")`
> 
> You might also add different JVM arguments, dependent on whether you are using release, or you are running it with jproRun:
> 
> ```
> JVMArgs << '-Djvmargument'
> localJVMArgs << '-Djvmargument'
> releaseJVMArgs << '-Djvmargument'
> ```

it worked. thank you.
