### ISSUE TITLE
How to apply gradle custom jar plugin?

### ISSUE THREAD

**Issue by harideva16** [JPro-one/HelloJPro#26]
I tried this [answer][1] to apply gradle custom jar plugin.

But , it not worked. 

My project : [jpro-custom-plugin][2]

What I did wrong in this ?

How to apply gradle custom jar plugin ?

  [1]: https://stackoverflow.com/a/16468836/16764874
  [2]: https://github.com/harideva16/jpro-custom-plugin

**Comment by FlorianKirmaier** [comment]
You are properly applying the custom jar plugin.

The question is, why does the plugin not work properly?
Maybe it's an old version? Or it runs into a corner case the developer didn't knowabout? It might also not be compatible with the latest Gradle version.

**Comment by harideva16** [comment]
thanks for your replay.
