### ISSUE TITLE
JPro with native library.

### ISSUE THREAD

**Issue by harideva16** [JPro-one/HelloJPro#29]
I build my JPro app with JNI successfully.

Java native interface (jni) allows calling native libraries

Windows --> .dll
Linux --> .so
Mac -->.dylib

https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#loadLibrary(java.lang.String)

I use the following code to load native library.

      static {
        System.loadLibrary("hellojpro");
        }

If I generate native library in windows os the native library's name comes `hellojpro.dll`

But , in Linux os the native library's name comes `libhellojpro.so` and in mac it comes `libhellojpro.dylib` 

Will this code ` System.loadLibrary("hellojpro");` load native library correcty after relesing jpro in linux and mac ?

**Comment by FlorianKirmaier** [comment]
I think so, but I don't know. I'm not an expert related to mixing native code with Java, nor is JPro really related to it - except that it can be combined.
Why don't you test it yourself? It's the easiest way to find out whether it works.

**Comment by harideva16** [comment]
> I think so, but I don't know. I'm not an expert related to mixing native code with Java, nor is JPro really related to it - except that it can be combined.
> Why don't you test it yourself? It's the easiest way to find out whether it works.

But , I have only one device with windows 10 os.

**Comment by FlorianKirmaier** [comment]
I've got bad news for you - you need an Linux/mac device available if you want to develop for these systems.

**Comment by Muhammad-Muddasir** [comment]
oi
