### ISSUE TITLE
Visible = false  issue

### ISSUE THREAD

**Issue by Timodz** [jpro-one/HelloJPro#4]
Hello, when i use this configuration 
```
jpro {
  port = 8083
  visible = false
  openURLOnStartup = false
}
```
its getting stuck at : `c.jpro.activity - Starting the server`
but when i set it to true it works fine but i get that java window too when the app starts in browser.
Thanks

**Comment by FlorianKirmaier** [comment]
Hi @Timodz

I'm sorry for the late answer.
Which version of JPro are you using?
Which version of Java is used?
Can you show me the whole output of the console?

**Comment by FlorianKirmaier** [comment]
I'm closing the ticket now.
